In [44]:
import pandas as pd

In [45]:
df = pd.read_csv("/content/titanic.csv")
df.head()

,PassengerId,Name,Pclass,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,Survived
0,1,"Braund, Mr. Owen Harris",3,male,22.0,1,0,A/5 21171,7.2500,NaN,S,0
1,2,"Cumings, Mrs. John Bradley (Florence Briggs Th...",1,female,38.0,1,0,PC 17599,71.2833,C85,C,1
2,3,"Heikkinen, Miss. Laina",3,female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S,1
3,4,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",1,female,35.0,1,0,113803,53.1000,C123,S,1
4,5,"Allen, Mr. William Henry",3,male,35.0,0,0,373450,8.0500,NaN,S,0

In [46]:
df.head()
df.columns

Index(['PassengerId', 'Name', 'Pclass', 'Sex', 'Age', 'SibSp', 'Parch',
       'Ticket', 'Fare', 'Cabin', 'Embarked', 'Survived'],
      dtype='object')

In [59]:
df.drop(['Ticket', 'PassengerId'],
        axis='columns',
        inplace=True)

In [47]:
X = df.drop('Survived', axis=1)
y = df['Survived']

In [48]:
X.head()

,PassengerId,Name,Pclass,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,"Braund, Mr. Owen Harris",3,male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,"Cumings, Mrs. John Bradley (Florence Briggs Th...",1,female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,"Heikkinen, Miss. Laina",3,female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",1,female,35.0,1,0,113803,53.1000,C123,S
4,5,"Allen, Mr. William Henry",3,male,35.0,0,0,373450,8.0500,NaN,S

In [49]:
dummies = pd.get_dummies(X['Sex'])

In [50]:
X = pd.concat([X,dummies], axis = 'columns')

In [51]:
X.drop('Sex', axis=1, inplace=True)

In [52]:
X

,PassengerId,Name,Pclass,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,female,male
0,1,"Braund, Mr. Owen Harris",3,22.0,1,0,A/5 21171,7.2500,NaN,S,False,True
1,2,"Cumings, Mrs. John Bradley (Florence Briggs Th...",1,38.0,1,0,PC 17599,71.2833,C85,C,True,False
2,3,"Heikkinen, Miss. Laina",3,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S,True,False
3,4,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",1,35.0,1,0,113803,53.1000,C123,S,True,False
4,5,"Allen, Mr. William Henry",3,35.0,0,0,373450,8.0500,NaN,S,False,True
...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,"Montvila, Rev. Juozas",2,27.0,0,0,211536,13.0000,NaN,S,False,True
887,888,"Graham, Miss. Margaret Edith",1,19.0,0,0,112053,30.0000,B42,S,True,False
888,889,"Johnston, Miss. Catherine Helen ""Carrie""",3,NaN,1,2,W./C. 6607,23.4500,NaN,S,True,False
889,890,"Behr, Mr. Karl Howell",1,26.0,0,0,111369,30.0000,C148,C,False,True
890,891,"Dooley, Mr. Patrick",3,32.0,0,0,370376,7.7500,NaN,Q,False,True

In [53]:
X.isnull().any()

PassengerId    False
Name           False
Pclass         False
Age             True
SibSp          False
Parch          False
Ticket         False
Fare           False
Cabin           True
Embarked        True
female         False
male           False
dtype: bool

In [54]:
X['Age'] =X['Age'].fillna(X['Age'].mean())

In [55]:
X.isnull().any()

PassengerId    False
Name           False
Pclass         False
Age            False
SibSp          False
Parch          False
Ticket         False
Fare           False
Cabin           True
Embarked        True
female         False
male           False
dtype: bool

In [56]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2)

In [57]:
from sklearn.naive_bayes import GaussianNB
model = GaussianNB()

In [61]:
X_train_processed = X_train.drop(['Name', 'Cabin', 'Embarked', 'Ticket', 'PassengerId'], axis=1)
X_train_processed['female'] = X_train_processed['female'].astype(int)
X_train_processed['male'] = X_train_processed['male'].astype(int)

model.fit(X_train_processed,y_train)

GaussianNB()

In [63]:
X_test_processed = X_test.drop(['Name', 'Cabin', 'Embarked', 'Ticket', 'PassengerId'], axis=1)
X_test_processed['female'] = X_test_processed['female'].astype(int)
X_test_processed['male'] = X_test_processed['male'].astype(int)

model.score(X_test_processed, y_test)

0.7932960893854749

In [64]:
from sklearn.metrics import classification_report

y_pred = model.predict(X_test_processed)
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.84      0.82      0.83       112
           1       0.71      0.75      0.73        67

    accuracy                           0.79       179
   macro avg       0.78      0.78      0.78       179
weighted avg       0.80      0.79      0.79       179